name: deploying vprofile application on EKS

on: workflow_dispatch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git
        uses: actions/checkout@v2

      - name: run tests
        run: mvn test

      - name: Building the code using maven
        run: mvn clean install -DskipTests

      - name: collect the checkstyle report
        run: mvn checkstyle:checkstyle

      - name: Scanning the code using sonar qube scanner
        uses: SonarSource/sonarqube-scan-action@v5.3.0
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.java.binaries=target/classes
            -Dsonar.junit.reportsPath=target/surefire-reports/
            -Dsonar.jacoco.reportsPath=target/jacoco.exec
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml

      - name: checking quality gate status
        uses: sonarsource/sonarqube-quality-gate-action@master
        continue-on-error: true
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Deploying:
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      repository: vprofile/vpro-images
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_region: eu-north-1
    steps:
      - name: checkout git
        uses: actions/checkout@v2

      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: vprofile/vpro-images
          tags: vprofile-tomcat-latest-${{ github.run_number }}
          registry: 906314669249.dkr.ecr.eu-north-1.amazonaws.com
          dockerfile: ./Dockerfile
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1

  Running-EKS:
    needs: Deploying
    runs-on: ubuntu-latest
    steps:
      - name: checkout git
        uses: actions/checkout@v2

      - name: Fetching kube config file
        run: |
          aws eks --region eu-north-1 update-kubeconfig --name vprofile-cluster
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1

      - name: setting up ecr creds
        run: |
          aws ecr get-login-password --region eu-north-1 | \
          kubectl create secret ecr-cred --docker-server=906314669249.dkr.ecr.eu-north-1.amazonaws.com --docker-username=AWS --docker-password-stdin
      #
      - name: setting up docker hub creds
        run: |
          kubectl create secret docker-cred --docker-server=https://index.docker.io/v1/ --docker-username=shaiksuhaildocker --docker-password=${{secrets.DOCKER_SECRET}} --docker-email=dilkushsuhail6786@gmail.com

      - name: Creating Helm charts and running the application
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.12
        with:
          kubeconfig: ${{ env.KUBECONFIG }}
          cluster-name: vprofile-cluster
          action: install
          name: vprofile-release
          namespace: default
          values: ./vprofile-charts/values.yaml
          wait: true
          timeout: 600
          install: true
          upgrade: true
