name: deploying vprofile application on EKS

on: workflow_dispatch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git
        uses: actions/checkout@v2

      - name: run tests
        run: mvn test

      - name: Building the code using maven
        run: mvn clean install -DskipTests

      - name: collect the checkstyle report
        run: mvn checkstyle:checkstyle

      - name: Scanning the code using sonar qube scanner
        uses: SonarSource/sonarqube-scan-action@v5.3.0
        with:
          projectBaseDir: ./src/
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.binaries=target/classes
            -Dsonar.junit.reportsPath=target/surefire-reports/
            -Dsonar.jacoco.reportsPath=target/jacoco.exec
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml

      - name: checking quality gate status
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
