name: deploying vprofile application on EKS

on: workflow_dispatch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git
        uses: actions/checkout@v2

      - name: run tests
        run: mvn test

      - name: Building the code using maven
        run: mvn clean install -DskipTests

      - name: collect the checkstyle report
        run: mvn checkstyle:checkstyle

      - name: Scanning the code using sonar qube scanner
        uses: SonarSource/sonarqube-scan-action@v5.3.0
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.java.binaries=target/classes
            -Dsonar.junit.reportsPath=target/surefire-reports/
            -Dsonar.jacoco.reportsPath=target/jacoco.exec
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml

      - name: checking quality gate status
        uses: sonarsource/sonarqube-quality-gate-action@master
        continue-on-error: true
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Deploying:
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      repository: vprofile/vpro-images
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_region: eu-north-1
    steps:
      - name: checkout git
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: private

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.repository }}
          IMAGE_TAG: latest:${{ github.run_number }}
          region: ${{ env.aws_region }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
